
import { Tables } from '../supabase/database.types.ts';
import { CastType } from './casts.ts';
export const CREATE_SQL = `CREATE TABLE undefined (
    id integer PRIMARY KEY,
    name text NOT NULL,
    icon integer NOT NULL,
    action_category integer NOT NULL,
    animation_start integer NOT NULL,
    vfx integer NOT NULL,
    animation_end integer NOT NULL,
    action_timeline_hit integer NOT NULL,
    class_job integer NOT NULL,
    behaviour_type smallint NOT NULL,
    class_job_level smallint NOT NULL,
    is_role_action boolean NOT NULL,
    range smallint NOT NULL,
    can_target_self boolean NOT NULL,
    can_target_party boolean NOT NULL,
    can_target_friendly boolean NOT NULL,
    can_target_hostile boolean NOT NULL,
    target_area boolean NOT NULL,
    can_target_dead boolean NOT NULL,
    cast_type smallint NOT NULL,
    effect_range smallint NOT NULL,
    xaxis_modifier smallint NOT NULL,
    primary_cost_type smallint NOT NULL,
    primary_cost_value integer NOT NULL,
    secondary_cost_type smallint NOT NULL,
    secondary_cost_value integer NOT NULL,
    action_combo integer NOT NULL,
    preserves_combo boolean NOT NULL,
    cast100ms integer NOT NULL,
    recast100ms integer NOT NULL,
    cooldown_group smallint NOT NULL,
    additional_cooldown_group smallint NOT NULL,
    max_charges smallint NOT NULL,
    attack_type integer NOT NULL,
    aspect smallint NOT NULL,
    action_proc_status integer NOT NULL,
    status_gain_self integer NOT NULL,
    unlock_link integer NOT NULL,
    class_job_category integer NOT NULL,
    affects_position boolean NOT NULL,
    omen integer NOT NULL,
    is_pvp boolean NOT NULL,
    is_player_action boolean NOT NULL
);`;

export type Action = {
  id: number,
  name: string,
  icon: number,
  actionCategory: number,
  animationStart: number,
  vfx: number,
  animationEnd: number,
  actionTimelineHit: number,
  classJob: number,
  behaviourType: number,
  classJobLevel: number,
  isRoleAction: boolean,
  range: number,
  canTargetSelf: boolean,
  canTargetParty: boolean,
  canTargetFriendly: boolean,
  canTargetHostile: boolean,
  targetArea: boolean,
  canTargetDead: boolean,
  castType: CastType,
  effectRange: number,
  xAxisModifier: number,
  primaryCostType: number,
  primaryCostValue: number,
  secondaryCostType: number,
  secondaryCostValue: number,
  actionCombo: number,
  preservesCombo: boolean,
  cast100ms: number,
  recast100ms: number,
  cooldownGroup: number,
  additionalCooldownGroup: number,
  maxCharges: number,
  attackType: number,
  aspect: number,
  actionProcStatus: number,
  statusGainSelf: number,
  unlockLink: number,
  classJobCategory: number,
  affectsPosition: boolean,
  omen: number,
  isPvP: boolean,
  isPlayerAction: boolean
};

export const unknownAction: Action = {
  id: -1,
  name: "<missing>",
  icon: -1,
  actionCategory: -1,
  animationStart: -1,
  vfx: -1,
  animationEnd: -1,
  actionTimelineHit: -1,
  classJob: -1,
  behaviourType: -1,
  classJobLevel: -1,
  isRoleAction: false,
  range: -1,
  canTargetSelf: false,
  canTargetParty: false,
  canTargetFriendly: false,
  canTargetHostile: false,
  targetArea: false,
  canTargetDead: false,
  castType: -1,
  effectRange: -1,
  xAxisModifier: -1,
  primaryCostType: -1,
  primaryCostValue: -1,
  secondaryCostType: -1,
  secondaryCostValue: -1,
  actionCombo: -1,
  preservesCombo: false,
  cast100ms: -1,
  recast100ms: -1,
  cooldownGroup: -1,
  additionalCooldownGroup: -1,
  maxCharges: -1,
  attackType: -1,
  aspect: -1,
  actionProcStatus: -1,
  statusGainSelf: -1,
  unlockLink: -1,
  classJobCategory: -1,
  affectsPosition: false,
  omen: -1,
  isPvP: false,
  isPlayerAction: false
}

export function fromSql(row: Tables<"actions">): Action {
  return {
    id: row.id,
    name: row.name,
    icon: row.icon,
    actionCategory: row.action_category,
    animationStart: row.animation_start,
    vfx: row.vfx,
    animationEnd: row.animation_end,
    actionTimelineHit: row.action_timeline_hit,
    classJob: row.class_job,
    behaviourType: row.behaviour_type,
    classJobLevel: row.class_job_level,
    isRoleAction: row.is_role_action,
    range: row.range,
    canTargetSelf: row.can_target_self,
    canTargetParty: row.can_target_party,
    canTargetFriendly: row.can_target_friendly,
    canTargetHostile: row.can_target_hostile,
    targetArea: row.target_area,
    canTargetDead: row.can_target_dead,
    castType: row.cast_type as CastType,
    effectRange: row.effect_range,
    xAxisModifier: row.xaxis_modifier,
    primaryCostType: row.primary_cost_type,
    primaryCostValue: row.primary_cost_value,
    secondaryCostType: row.secondary_cost_type,
    secondaryCostValue: row.secondary_cost_value,
    actionCombo: row.action_combo,
    preservesCombo: row.preserves_combo,
    cast100ms: row.cast100ms,
    recast100ms: row.recast100ms,
    cooldownGroup: row.cooldown_group,
    additionalCooldownGroup: row.additional_cooldown_group,
    maxCharges: row.max_charges,
    attackType: row.attack_type,
    aspect: row.aspect,
    actionProcStatus: row.action_proc_status,
    statusGainSelf: row.status_gain_self,
    unlockLink: row.unlock_link,
    classJobCategory: row.class_job_category,
    affectsPosition: row.affects_position,
    omen: row.omen,
    isPvP: row.is_pvp,
    isPlayerAction: row.is_player_action
  };
}
  