/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as WorkertestImport } from "./routes/workertest";
import { Route as TestImport } from "./routes/test";
import { Route as PlantestImport } from "./routes/plantest";
import { Route as PlansImport } from "./routes/plans";
import { Route as NotesImport } from "./routes/notes";
import { Route as NonsenseImport } from "./routes/nonsense";
import { Route as MacroImport } from "./routes/macro";
import { Route as ImporttestImport } from "./routes/importtest";
import { Route as FusedownImport } from "./routes/fusedown";
import { Route as ClipboardImport } from "./routes/clipboard";
import { Route as AuthstartImport } from "./routes/auth_start";
import { Route as AuthredirectImport } from "./routes/auth_redirect";
import { Route as AnalysisImport } from "./routes/analysis";
import { Route as NotesIndexImport } from "./routes/notes/index";
import { Route as MacroIndexImport } from "./routes/macro/index";
import { Route as AnalysisIndexImport } from "./routes/analysis/index";
import { Route as PlansPlanIDImport } from "./routes/plans/$planID";
import { Route as NotesNoteIDImport } from "./routes/notes/$noteID";
import { Route as MacroMacroIDImport } from "./routes/macro/$macroID";
import { Route as AnalysisImportImport } from "./routes/analysis/import";
import { Route as AnalysisReportIDImport } from "./routes/analysis/$reportID";
import { Route as AnalysisReportIDIndexImport } from "./routes/analysis/$reportID/index";
import { Route as AnalysisTimelineReportIDImport } from "./routes/analysis/timeline/$reportID";
import { Route as AnalysisImportWorkerImport } from "./routes/analysis/import.worker";
import { Route as AnalysisImportFunctionsImport } from "./routes/analysis/import.functions";
import { Route as AnalysisAacm2sHeartsImport } from "./routes/analysis/aacm2s/hearts";
import { Route as AnalysisAacm2sBeesImport } from "./routes/analysis/aacm2s/bees";
import { Route as AnalysisReportIDTimelineImport } from "./routes/analysis/$reportID/timeline";
import { Route as AnalysisReportIDActionsImport } from "./routes/analysis/$reportID/actions";
import { Route as AnalysisReportIDFightIDImport } from "./routes/analysis/$reportID/$fightID";
import { Route as AnalysisAacm2sBeesReportIDImport } from "./routes/analysis/aacm2s/bees/$reportID";
import { Route as AnalysisReportIDFightIDEventsImport } from "./routes/analysis/$reportID/$fightID/events";
import { Route as AnalysisAacm2sBeesReportIDIndexImport } from "./routes/analysis/aacm2s/bees/$reportID/index";
import { Route as AnalysisAacm2sBeesReportIDFightIDImport } from "./routes/analysis/aacm2s/bees/$reportID/$fightID";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();

// Create/Update Routes

const WorkertestRoute = WorkertestImport.update({
  path: "/workertest",
  getParentRoute: () => rootRoute,
} as any);

const TestRoute = TestImport.update({
  path: "/test",
  getParentRoute: () => rootRoute,
} as any);

const PlantestRoute = PlantestImport.update({
  path: "/plantest",
  getParentRoute: () => rootRoute,
} as any);

const PlansRoute = PlansImport.update({
  path: "/plans",
  getParentRoute: () => rootRoute,
} as any);

const NotesRoute = NotesImport.update({
  path: "/notes",
  getParentRoute: () => rootRoute,
} as any);

const NonsenseRoute = NonsenseImport.update({
  path: "/nonsense",
  getParentRoute: () => rootRoute,
} as any);

const MacroRoute = MacroImport.update({
  path: "/macro",
  getParentRoute: () => rootRoute,
} as any);

const ImporttestRoute = ImporttestImport.update({
  path: "/importtest",
  getParentRoute: () => rootRoute,
} as any);

const FusedownRoute = FusedownImport.update({
  path: "/fusedown",
  getParentRoute: () => rootRoute,
} as any);

const ClipboardRoute = ClipboardImport.update({
  path: "/clipboard",
  getParentRoute: () => rootRoute,
} as any);

const AuthstartRoute = AuthstartImport.update({
  path: "/auth_start",
  getParentRoute: () => rootRoute,
} as any);

const AuthredirectRoute = AuthredirectImport.update({
  path: "/auth_redirect",
  getParentRoute: () => rootRoute,
} as any);

const AnalysisRoute = AnalysisImport.update({
  path: "/analysis",
  getParentRoute: () => rootRoute,
} as any);

const IndexLazyRoute = IndexLazyImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const NotesIndexRoute = NotesIndexImport.update({
  path: "/",
  getParentRoute: () => NotesRoute,
} as any);

const MacroIndexRoute = MacroIndexImport.update({
  path: "/",
  getParentRoute: () => MacroRoute,
} as any);

const AnalysisIndexRoute = AnalysisIndexImport.update({
  path: "/",
  getParentRoute: () => AnalysisRoute,
} as any);

const PlansPlanIDRoute = PlansPlanIDImport.update({
  path: "/$planID",
  getParentRoute: () => PlansRoute,
} as any);

const NotesNoteIDRoute = NotesNoteIDImport.update({
  path: "/$noteID",
  getParentRoute: () => NotesRoute,
} as any);

const MacroMacroIDRoute = MacroMacroIDImport.update({
  path: "/$macroID",
  getParentRoute: () => MacroRoute,
} as any);

const AnalysisImportRoute = AnalysisImportImport.update({
  path: "/import",
  getParentRoute: () => AnalysisRoute,
} as any);

const AnalysisReportIDRoute = AnalysisReportIDImport.update({
  path: "/$reportID",
  getParentRoute: () => AnalysisRoute,
} as any);

const AnalysisReportIDIndexRoute = AnalysisReportIDIndexImport.update({
  path: "/",
  getParentRoute: () => AnalysisReportIDRoute,
} as any);

const AnalysisTimelineReportIDRoute = AnalysisTimelineReportIDImport.update({
  path: "/timeline/$reportID",
  getParentRoute: () => AnalysisRoute,
} as any);

const AnalysisImportWorkerRoute = AnalysisImportWorkerImport.update({
  path: "/worker",
  getParentRoute: () => AnalysisImportRoute,
} as any);

const AnalysisImportFunctionsRoute = AnalysisImportFunctionsImport.update({
  path: "/functions",
  getParentRoute: () => AnalysisImportRoute,
} as any);

const AnalysisAacm2sHeartsRoute = AnalysisAacm2sHeartsImport.update({
  path: "/aacm2s/hearts",
  getParentRoute: () => AnalysisRoute,
} as any);

const AnalysisAacm2sBeesRoute = AnalysisAacm2sBeesImport.update({
  path: "/aacm2s/bees",
  getParentRoute: () => AnalysisRoute,
} as any);

const AnalysisReportIDTimelineRoute = AnalysisReportIDTimelineImport.update({
  path: "/timeline",
  getParentRoute: () => AnalysisReportIDRoute,
} as any);

const AnalysisReportIDActionsRoute = AnalysisReportIDActionsImport.update({
  path: "/actions",
  getParentRoute: () => AnalysisReportIDRoute,
} as any);

const AnalysisReportIDFightIDRoute = AnalysisReportIDFightIDImport.update({
  path: "/$fightID",
  getParentRoute: () => AnalysisReportIDRoute,
} as any);

const AnalysisAacm2sBeesReportIDRoute = AnalysisAacm2sBeesReportIDImport.update(
  {
    path: "/$reportID",
    getParentRoute: () => AnalysisAacm2sBeesRoute,
  } as any,
);

const AnalysisReportIDFightIDEventsRoute =
  AnalysisReportIDFightIDEventsImport.update({
    path: "/events",
    getParentRoute: () => AnalysisReportIDFightIDRoute,
  } as any);

const AnalysisAacm2sBeesReportIDIndexRoute =
  AnalysisAacm2sBeesReportIDIndexImport.update({
    path: "/",
    getParentRoute: () => AnalysisAacm2sBeesReportIDRoute,
  } as any);

const AnalysisAacm2sBeesReportIDFightIDRoute =
  AnalysisAacm2sBeesReportIDFightIDImport.update({
    path: "/$fightID",
    getParentRoute: () => AnalysisAacm2sBeesReportIDRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/analysis": {
      id: "/analysis";
      path: "/analysis";
      fullPath: "/analysis";
      preLoaderRoute: typeof AnalysisImport;
      parentRoute: typeof rootRoute;
    };
    "/auth_redirect": {
      id: "/auth_redirect";
      path: "/auth_redirect";
      fullPath: "/auth_redirect";
      preLoaderRoute: typeof AuthredirectImport;
      parentRoute: typeof rootRoute;
    };
    "/auth_start": {
      id: "/auth_start";
      path: "/auth_start";
      fullPath: "/auth_start";
      preLoaderRoute: typeof AuthstartImport;
      parentRoute: typeof rootRoute;
    };
    "/clipboard": {
      id: "/clipboard";
      path: "/clipboard";
      fullPath: "/clipboard";
      preLoaderRoute: typeof ClipboardImport;
      parentRoute: typeof rootRoute;
    };
    "/fusedown": {
      id: "/fusedown";
      path: "/fusedown";
      fullPath: "/fusedown";
      preLoaderRoute: typeof FusedownImport;
      parentRoute: typeof rootRoute;
    };
    "/importtest": {
      id: "/importtest";
      path: "/importtest";
      fullPath: "/importtest";
      preLoaderRoute: typeof ImporttestImport;
      parentRoute: typeof rootRoute;
    };
    "/macro": {
      id: "/macro";
      path: "/macro";
      fullPath: "/macro";
      preLoaderRoute: typeof MacroImport;
      parentRoute: typeof rootRoute;
    };
    "/nonsense": {
      id: "/nonsense";
      path: "/nonsense";
      fullPath: "/nonsense";
      preLoaderRoute: typeof NonsenseImport;
      parentRoute: typeof rootRoute;
    };
    "/notes": {
      id: "/notes";
      path: "/notes";
      fullPath: "/notes";
      preLoaderRoute: typeof NotesImport;
      parentRoute: typeof rootRoute;
    };
    "/plans": {
      id: "/plans";
      path: "/plans";
      fullPath: "/plans";
      preLoaderRoute: typeof PlansImport;
      parentRoute: typeof rootRoute;
    };
    "/plantest": {
      id: "/plantest";
      path: "/plantest";
      fullPath: "/plantest";
      preLoaderRoute: typeof PlantestImport;
      parentRoute: typeof rootRoute;
    };
    "/test": {
      id: "/test";
      path: "/test";
      fullPath: "/test";
      preLoaderRoute: typeof TestImport;
      parentRoute: typeof rootRoute;
    };
    "/workertest": {
      id: "/workertest";
      path: "/workertest";
      fullPath: "/workertest";
      preLoaderRoute: typeof WorkertestImport;
      parentRoute: typeof rootRoute;
    };
    "/analysis/$reportID": {
      id: "/analysis/$reportID";
      path: "/$reportID";
      fullPath: "/analysis/$reportID";
      preLoaderRoute: typeof AnalysisReportIDImport;
      parentRoute: typeof AnalysisImport;
    };
    "/analysis/import": {
      id: "/analysis/import";
      path: "/import";
      fullPath: "/analysis/import";
      preLoaderRoute: typeof AnalysisImportImport;
      parentRoute: typeof AnalysisImport;
    };
    "/macro/$macroID": {
      id: "/macro/$macroID";
      path: "/$macroID";
      fullPath: "/macro/$macroID";
      preLoaderRoute: typeof MacroMacroIDImport;
      parentRoute: typeof MacroImport;
    };
    "/notes/$noteID": {
      id: "/notes/$noteID";
      path: "/$noteID";
      fullPath: "/notes/$noteID";
      preLoaderRoute: typeof NotesNoteIDImport;
      parentRoute: typeof NotesImport;
    };
    "/plans/$planID": {
      id: "/plans/$planID";
      path: "/$planID";
      fullPath: "/plans/$planID";
      preLoaderRoute: typeof PlansPlanIDImport;
      parentRoute: typeof PlansImport;
    };
    "/analysis/": {
      id: "/analysis/";
      path: "/";
      fullPath: "/analysis/";
      preLoaderRoute: typeof AnalysisIndexImport;
      parentRoute: typeof AnalysisImport;
    };
    "/macro/": {
      id: "/macro/";
      path: "/";
      fullPath: "/macro/";
      preLoaderRoute: typeof MacroIndexImport;
      parentRoute: typeof MacroImport;
    };
    "/notes/": {
      id: "/notes/";
      path: "/";
      fullPath: "/notes/";
      preLoaderRoute: typeof NotesIndexImport;
      parentRoute: typeof NotesImport;
    };
    "/analysis/$reportID/$fightID": {
      id: "/analysis/$reportID/$fightID";
      path: "/$fightID";
      fullPath: "/analysis/$reportID/$fightID";
      preLoaderRoute: typeof AnalysisReportIDFightIDImport;
      parentRoute: typeof AnalysisReportIDImport;
    };
    "/analysis/$reportID/actions": {
      id: "/analysis/$reportID/actions";
      path: "/actions";
      fullPath: "/analysis/$reportID/actions";
      preLoaderRoute: typeof AnalysisReportIDActionsImport;
      parentRoute: typeof AnalysisReportIDImport;
    };
    "/analysis/$reportID/timeline": {
      id: "/analysis/$reportID/timeline";
      path: "/timeline";
      fullPath: "/analysis/$reportID/timeline";
      preLoaderRoute: typeof AnalysisReportIDTimelineImport;
      parentRoute: typeof AnalysisReportIDImport;
    };
    "/analysis/aacm2s/bees": {
      id: "/analysis/aacm2s/bees";
      path: "/aacm2s/bees";
      fullPath: "/analysis/aacm2s/bees";
      preLoaderRoute: typeof AnalysisAacm2sBeesImport;
      parentRoute: typeof AnalysisImport;
    };
    "/analysis/aacm2s/hearts": {
      id: "/analysis/aacm2s/hearts";
      path: "/aacm2s/hearts";
      fullPath: "/analysis/aacm2s/hearts";
      preLoaderRoute: typeof AnalysisAacm2sHeartsImport;
      parentRoute: typeof AnalysisImport;
    };
    "/analysis/import/functions": {
      id: "/analysis/import/functions";
      path: "/functions";
      fullPath: "/analysis/import/functions";
      preLoaderRoute: typeof AnalysisImportFunctionsImport;
      parentRoute: typeof AnalysisImportImport;
    };
    "/analysis/import/worker": {
      id: "/analysis/import/worker";
      path: "/worker";
      fullPath: "/analysis/import/worker";
      preLoaderRoute: typeof AnalysisImportWorkerImport;
      parentRoute: typeof AnalysisImportImport;
    };
    "/analysis/timeline/$reportID": {
      id: "/analysis/timeline/$reportID";
      path: "/timeline/$reportID";
      fullPath: "/analysis/timeline/$reportID";
      preLoaderRoute: typeof AnalysisTimelineReportIDImport;
      parentRoute: typeof AnalysisImport;
    };
    "/analysis/$reportID/": {
      id: "/analysis/$reportID/";
      path: "/";
      fullPath: "/analysis/$reportID/";
      preLoaderRoute: typeof AnalysisReportIDIndexImport;
      parentRoute: typeof AnalysisReportIDImport;
    };
    "/analysis/$reportID/$fightID/events": {
      id: "/analysis/$reportID/$fightID/events";
      path: "/events";
      fullPath: "/analysis/$reportID/$fightID/events";
      preLoaderRoute: typeof AnalysisReportIDFightIDEventsImport;
      parentRoute: typeof AnalysisReportIDFightIDImport;
    };
    "/analysis/aacm2s/bees/$reportID": {
      id: "/analysis/aacm2s/bees/$reportID";
      path: "/$reportID";
      fullPath: "/analysis/aacm2s/bees/$reportID";
      preLoaderRoute: typeof AnalysisAacm2sBeesReportIDImport;
      parentRoute: typeof AnalysisAacm2sBeesImport;
    };
    "/analysis/aacm2s/bees/$reportID/$fightID": {
      id: "/analysis/aacm2s/bees/$reportID/$fightID";
      path: "/$fightID";
      fullPath: "/analysis/aacm2s/bees/$reportID/$fightID";
      preLoaderRoute: typeof AnalysisAacm2sBeesReportIDFightIDImport;
      parentRoute: typeof AnalysisAacm2sBeesReportIDImport;
    };
    "/analysis/aacm2s/bees/$reportID/": {
      id: "/analysis/aacm2s/bees/$reportID/";
      path: "/";
      fullPath: "/analysis/aacm2s/bees/$reportID/";
      preLoaderRoute: typeof AnalysisAacm2sBeesReportIDIndexImport;
      parentRoute: typeof AnalysisAacm2sBeesReportIDImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AnalysisRoute: AnalysisRoute.addChildren({
    AnalysisReportIDRoute: AnalysisReportIDRoute.addChildren({
      AnalysisReportIDFightIDRoute: AnalysisReportIDFightIDRoute.addChildren({
        AnalysisReportIDFightIDEventsRoute,
      }),
      AnalysisReportIDActionsRoute,
      AnalysisReportIDTimelineRoute,
      AnalysisReportIDIndexRoute,
    }),
    AnalysisImportRoute: AnalysisImportRoute.addChildren({
      AnalysisImportFunctionsRoute,
      AnalysisImportWorkerRoute,
    }),
    AnalysisIndexRoute,
    AnalysisAacm2sBeesRoute: AnalysisAacm2sBeesRoute.addChildren({
      AnalysisAacm2sBeesReportIDRoute:
        AnalysisAacm2sBeesReportIDRoute.addChildren({
          AnalysisAacm2sBeesReportIDFightIDRoute,
          AnalysisAacm2sBeesReportIDIndexRoute,
        }),
    }),
    AnalysisAacm2sHeartsRoute,
    AnalysisTimelineReportIDRoute,
  }),
  AuthredirectRoute,
  AuthstartRoute,
  ClipboardRoute,
  FusedownRoute,
  ImporttestRoute,
  MacroRoute: MacroRoute.addChildren({ MacroMacroIDRoute, MacroIndexRoute }),
  NonsenseRoute,
  NotesRoute: NotesRoute.addChildren({ NotesNoteIDRoute, NotesIndexRoute }),
  PlansRoute: PlansRoute.addChildren({ PlansPlanIDRoute }),
  PlantestRoute,
  TestRoute,
  WorkertestRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analysis",
        "/auth_redirect",
        "/auth_start",
        "/clipboard",
        "/fusedown",
        "/importtest",
        "/macro",
        "/nonsense",
        "/notes",
        "/plans",
        "/plantest",
        "/test",
        "/workertest"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/analysis": {
      "filePath": "analysis.tsx",
      "children": [
        "/analysis/$reportID",
        "/analysis/import",
        "/analysis/",
        "/analysis/aacm2s/bees",
        "/analysis/aacm2s/hearts",
        "/analysis/timeline/$reportID"
      ]
    },
    "/auth_redirect": {
      "filePath": "auth_redirect.tsx"
    },
    "/auth_start": {
      "filePath": "auth_start.tsx"
    },
    "/clipboard": {
      "filePath": "clipboard.tsx"
    },
    "/fusedown": {
      "filePath": "fusedown.tsx"
    },
    "/importtest": {
      "filePath": "importtest.tsx"
    },
    "/macro": {
      "filePath": "macro.tsx",
      "children": [
        "/macro/$macroID",
        "/macro/"
      ]
    },
    "/nonsense": {
      "filePath": "nonsense.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx",
      "children": [
        "/notes/$noteID",
        "/notes/"
      ]
    },
    "/plans": {
      "filePath": "plans.tsx",
      "children": [
        "/plans/$planID"
      ]
    },
    "/plantest": {
      "filePath": "plantest.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/workertest": {
      "filePath": "workertest.tsx"
    },
    "/analysis/$reportID": {
      "filePath": "analysis/$reportID.tsx",
      "parent": "/analysis",
      "children": [
        "/analysis/$reportID/$fightID",
        "/analysis/$reportID/actions",
        "/analysis/$reportID/timeline",
        "/analysis/$reportID/"
      ]
    },
    "/analysis/import": {
      "filePath": "analysis/import.tsx",
      "parent": "/analysis",
      "children": [
        "/analysis/import/functions",
        "/analysis/import/worker"
      ]
    },
    "/macro/$macroID": {
      "filePath": "macro/$macroID.tsx",
      "parent": "/macro"
    },
    "/notes/$noteID": {
      "filePath": "notes/$noteID.tsx",
      "parent": "/notes"
    },
    "/plans/$planID": {
      "filePath": "plans/$planID.tsx",
      "parent": "/plans"
    },
    "/analysis/": {
      "filePath": "analysis/index.tsx",
      "parent": "/analysis"
    },
    "/macro/": {
      "filePath": "macro/index.tsx",
      "parent": "/macro"
    },
    "/notes/": {
      "filePath": "notes/index.tsx",
      "parent": "/notes"
    },
    "/analysis/$reportID/$fightID": {
      "filePath": "analysis/$reportID/$fightID.tsx",
      "parent": "/analysis/$reportID",
      "children": [
        "/analysis/$reportID/$fightID/events"
      ]
    },
    "/analysis/$reportID/actions": {
      "filePath": "analysis/$reportID/actions.tsx",
      "parent": "/analysis/$reportID"
    },
    "/analysis/$reportID/timeline": {
      "filePath": "analysis/$reportID/timeline.tsx",
      "parent": "/analysis/$reportID"
    },
    "/analysis/aacm2s/bees": {
      "filePath": "analysis/aacm2s/bees.tsx",
      "parent": "/analysis",
      "children": [
        "/analysis/aacm2s/bees/$reportID"
      ]
    },
    "/analysis/aacm2s/hearts": {
      "filePath": "analysis/aacm2s/hearts.tsx",
      "parent": "/analysis"
    },
    "/analysis/import/functions": {
      "filePath": "analysis/import.functions.tsx",
      "parent": "/analysis/import"
    },
    "/analysis/import/worker": {
      "filePath": "analysis/import.worker.tsx",
      "parent": "/analysis/import"
    },
    "/analysis/timeline/$reportID": {
      "filePath": "analysis/timeline/$reportID.tsx",
      "parent": "/analysis"
    },
    "/analysis/$reportID/": {
      "filePath": "analysis/$reportID/index.tsx",
      "parent": "/analysis/$reportID"
    },
    "/analysis/$reportID/$fightID/events": {
      "filePath": "analysis/$reportID/$fightID/events.tsx",
      "parent": "/analysis/$reportID/$fightID"
    },
    "/analysis/aacm2s/bees/$reportID": {
      "filePath": "analysis/aacm2s/bees/$reportID.tsx",
      "parent": "/analysis/aacm2s/bees",
      "children": [
        "/analysis/aacm2s/bees/$reportID/$fightID",
        "/analysis/aacm2s/bees/$reportID/"
      ]
    },
    "/analysis/aacm2s/bees/$reportID/$fightID": {
      "filePath": "analysis/aacm2s/bees/$reportID/$fightID.tsx",
      "parent": "/analysis/aacm2s/bees/$reportID"
    },
    "/analysis/aacm2s/bees/$reportID/": {
      "filePath": "analysis/aacm2s/bees/$reportID/index.tsx",
      "parent": "/analysis/aacm2s/bees/$reportID"
    }
  }
}
ROUTE_MANIFEST_END */
