drop policy "edit own reports" on "analysis"."fight_events";

drop policy "edit own reports" on "analysis"."report_actors";

drop policy "access own reports" on "analysis"."report_fights";

drop policy "Access own reports" on "analysis"."reports";

alter table "analysis"."fight_events" drop constraint "fight_events_fight_id_fkey";

alter table "analysis"."report_actors" drop constraint "report_actors_report_id_fkey";

alter table "analysis"."report_fights" drop constraint "report_fights_report_id_fkey";

alter table "analysis"."fight_events" drop constraint "fight_events_pkey";

alter table "analysis"."report_actors" drop constraint "report_actors_pkey";

alter table "analysis"."report_fights" drop constraint "report_fights_pkey";

alter table "analysis"."reports" drop constraint "reports_pkey";

drop index if exists "analysis"."fight_events_pkey";

drop index if exists "analysis"."report_actors_pkey";

drop index if exists "analysis"."report_fights_pkey";

drop index if exists "analysis"."reports_pkey";

drop table "analysis"."fight_events";

drop table "analysis"."report_actors";

drop table "analysis"."report_fights";

drop table "analysis"."reports";


create table "public"."fight_events" (
    "id" bigint generated by default as identity not null,
    "fight_id" bigint not null,
    "timestamp" bigint not null,
    "type" text not null,
    "source_id" bigint,
    "source_instance" smallint,
    "target_id" bigint,
    "target_instance" smallint,
    "action_id" integer
);


alter table "public"."fight_events" enable row level security;

create table "public"."report_actors" (
    "id" bigint not null,
    "report_id" bigint not null,
    "game_id" bigint,
    "name" text not null,
    "type" text not null,
    "subtype" text not null
);


alter table "public"."report_actors" enable row level security;

create table "public"."report_fights" (
    "id" bigint generated by default as identity not null,
    "report_id" bigint not null,
    "name" text not null,
    "start_time" timestamp without time zone not null,
    "end_time" timestamp without time zone not null,
    "encounter_id" integer not null,
    "in_progress" boolean not null,
    "zone_id" integer not null,
    "zone_name" text not null,
    "combat_time" bigint not null,
    "boss_percentage" smallint not null,
    "locator_data" jsonb,
    "actions" integer[] not null,
    "actors" integer[] not null,
    "fight_number" smallint not null
);


alter table "public"."report_fights" enable row level security;

create table "public"."reports" (
    "id" bigint generated by default as identity not null,
    "owner" uuid,
    "code" text not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text default ''::text,
    "start_time" timestamp without time zone not null,
    "end_time" timestamp without time zone not null
);


alter table "public"."reports" enable row level security;

CREATE UNIQUE INDEX fight_events_pkey ON public.fight_events USING btree (id);

CREATE UNIQUE INDEX report_actors_pkey ON public.report_actors USING btree (id, report_id);

CREATE UNIQUE INDEX report_fights_pkey ON public.report_fights USING btree (id);

CREATE UNIQUE INDEX reports_pkey ON public.reports USING btree (id);

alter table "public"."fight_events" add constraint "fight_events_pkey" PRIMARY KEY using index "fight_events_pkey";

alter table "public"."report_actors" add constraint "report_actors_pkey" PRIMARY KEY using index "report_actors_pkey";

alter table "public"."report_fights" add constraint "report_fights_pkey" PRIMARY KEY using index "report_fights_pkey";

alter table "public"."reports" add constraint "reports_pkey" PRIMARY KEY using index "reports_pkey";

alter table "public"."fight_events" add constraint "fight_events_fight_id_fkey" FOREIGN KEY (fight_id) REFERENCES report_fights(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."fight_events" validate constraint "fight_events_fight_id_fkey";

alter table "public"."report_actors" add constraint "report_actors_report_id_fkey" FOREIGN KEY (report_id) REFERENCES reports(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."report_actors" validate constraint "report_actors_report_id_fkey";

alter table "public"."report_fights" add constraint "report_fights_report_id_fkey" FOREIGN KEY (report_id) REFERENCES reports(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."report_fights" validate constraint "report_fights_report_id_fkey";

create policy "edit own reports"
on "public"."fight_events"
as permissive
for all
to authenticated
using ((( SELECT auth.uid() AS uid) = ( SELECT reports.owner
   FROM reports
  WHERE (reports.id = ( SELECT report_fights.report_id
           FROM report_fights
          WHERE (report_fights.id = fight_events.fight_id))))))
with check ((( SELECT auth.uid() AS uid) = ( SELECT reports.owner
   FROM reports
  WHERE (reports.id = ( SELECT report_fights.report_id
           FROM report_fights
          WHERE (report_fights.id = fight_events.fight_id))))));


create policy "edit own reports"
on "public"."report_actors"
as permissive
for all
to authenticated
using ((( SELECT auth.uid() AS uid) = ( SELECT reports.owner
   FROM reports
  WHERE (reports.id = report_actors.report_id))))
with check ((( SELECT auth.uid() AS uid) = ( SELECT reports.owner
   FROM reports
  WHERE (reports.id = report_actors.report_id))));


create policy "access own reports"
on "public"."report_fights"
as permissive
for all
to authenticated
using ((( SELECT auth.uid() AS uid) = ( SELECT reports.owner
   FROM reports
  WHERE (reports.id = report_fights.report_id))))
with check ((( SELECT auth.uid() AS uid) = ( SELECT reports.owner
   FROM reports
  WHERE (reports.id = report_fights.report_id))));


create policy "Access own reports"
on "public"."reports"
as permissive
for all
to authenticated
using ((( SELECT auth.uid() AS uid) = owner))
with check ((( SELECT auth.uid() AS uid) = owner));



