

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "analysis";


ALTER SCHEMA "analysis" OWNER TO "postgres";


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "analysis"."fight_events" (
    "id" bigint NOT NULL,
    "fight_id" bigint NOT NULL,
    "timestamp" bigint NOT NULL,
    "type" "text" NOT NULL,
    "source_id" bigint,
    "source_instance" smallint,
    "target_id" bigint,
    "target_instance" smallint,
    "action_id" integer
);


ALTER TABLE "analysis"."fight_events" OWNER TO "postgres";


COMMENT ON TABLE "analysis"."fight_events" IS 'All the events in a single fight of a report';



ALTER TABLE "analysis"."fight_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "analysis"."fight_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "analysis"."report_actors" (
    "id" bigint NOT NULL,
    "report_id" bigint NOT NULL,
    "game_id" bigint,
    "name" "text" NOT NULL,
    "type" "text" NOT NULL,
    "subtype" "text" NOT NULL
);


ALTER TABLE "analysis"."report_actors" OWNER TO "postgres";


COMMENT ON TABLE "analysis"."report_actors" IS 'All actors seen in a single report';



CREATE TABLE IF NOT EXISTS "analysis"."report_fights" (
    "id" bigint NOT NULL,
    "report_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "start_time" timestamp without time zone NOT NULL,
    "end_time" timestamp without time zone NOT NULL,
    "encounter_id" integer NOT NULL,
    "in_progress" boolean NOT NULL,
    "zone_id" integer NOT NULL,
    "zone_name" "text" NOT NULL,
    "combat_time" bigint NOT NULL,
    "boss_percentage" smallint NOT NULL,
    "locator_data" "jsonb",
    "actions" integer[] NOT NULL,
    "actors" integer[] NOT NULL,
    "fight_number" smallint NOT NULL
);


ALTER TABLE "analysis"."report_fights" OWNER TO "postgres";


COMMENT ON TABLE "analysis"."report_fights" IS 'A single fight in a report';



ALTER TABLE "analysis"."report_fights" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "analysis"."report_fights_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "analysis"."reports" (
    "id" bigint NOT NULL,
    "owner" "uuid",
    "code" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" DEFAULT ''::"text",
    "start_time" timestamp without time zone NOT NULL,
    "end_time" timestamp without time zone NOT NULL
);


ALTER TABLE "analysis"."reports" OWNER TO "postgres";


COMMENT ON TABLE "analysis"."reports" IS 'A single analysed report';



ALTER TABLE "analysis"."reports" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "analysis"."reports_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."actions" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "icon" integer NOT NULL,
    "action_category" integer NOT NULL,
    "animation_start" integer NOT NULL,
    "vfx" integer NOT NULL,
    "animation_end" integer NOT NULL,
    "action_timeline_hit" integer NOT NULL,
    "class_job" integer NOT NULL,
    "behaviour_type" smallint NOT NULL,
    "class_job_level" smallint NOT NULL,
    "is_role_action" boolean NOT NULL,
    "range" smallint NOT NULL,
    "can_target_self" boolean NOT NULL,
    "can_target_party" boolean NOT NULL,
    "can_target_friendly" boolean NOT NULL,
    "can_target_hostile" boolean NOT NULL,
    "target_area" boolean NOT NULL,
    "can_target_dead" boolean NOT NULL,
    "cast_type" smallint NOT NULL,
    "effect_range" smallint NOT NULL,
    "xaxis_modifier" smallint NOT NULL,
    "primary_cost_type" smallint NOT NULL,
    "primary_cost_value" integer NOT NULL,
    "secondary_cost_type" smallint NOT NULL,
    "secondary_cost_value" integer NOT NULL,
    "action_combo" integer NOT NULL,
    "preserves_combo" boolean NOT NULL,
    "cast100ms" integer NOT NULL,
    "recast100ms" integer NOT NULL,
    "cooldown_group" smallint NOT NULL,
    "additional_cooldown_group" smallint NOT NULL,
    "max_charges" smallint NOT NULL,
    "attack_type" integer NOT NULL,
    "aspect" smallint NOT NULL,
    "action_proc_status" integer NOT NULL,
    "status_gain_self" integer NOT NULL,
    "unlock_link" integer NOT NULL,
    "class_job_category" integer NOT NULL,
    "affects_position" boolean NOT NULL,
    "omen" integer NOT NULL,
    "is_pvp" boolean NOT NULL,
    "is_player_action" boolean NOT NULL
);


ALTER TABLE "public"."actions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."actions2" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "_unknown_2" boolean NOT NULL,
    "icon" integer NOT NULL,
    "action_category" integer NOT NULL,
    "_unknown_5" smallint NOT NULL,
    "animation_start" integer NOT NULL,
    "vfx" integer NOT NULL,
    "animation_end" integer NOT NULL,
    "action_timeline_hit" integer NOT NULL,
    "_unknown_10" smallint NOT NULL,
    "class_job" integer NOT NULL,
    "behaviour_type" smallint NOT NULL,
    "class_job_level" smallint NOT NULL,
    "is_role_action" boolean NOT NULL,
    "range" smallint NOT NULL,
    "can_target_self" boolean NOT NULL,
    "can_target_party" boolean NOT NULL,
    "can_target_friendly" boolean NOT NULL,
    "can_target_hostile" boolean NOT NULL,
    "_unknown_20" boolean NOT NULL,
    "_unknown_21" boolean NOT NULL,
    "target_area" boolean NOT NULL,
    "_unknown_23" boolean NOT NULL,
    "_unknown_24" boolean NOT NULL,
    "_unknown_25" smallint NOT NULL,
    "can_target_dead" boolean NOT NULL,
    "_unknown_27" boolean NOT NULL,
    "cast_type" smallint NOT NULL,
    "effect_range" smallint NOT NULL,
    "xaxis_modifier" smallint NOT NULL,
    "_unknown_31" boolean NOT NULL,
    "primary_cost_type" smallint NOT NULL,
    "primary_cost_value" integer NOT NULL,
    "secondary_cost_type" smallint NOT NULL,
    "secondary_cost_value" integer NOT NULL,
    "action_combo" integer NOT NULL,
    "preserves_combo" boolean NOT NULL,
    "cast100ms" integer NOT NULL,
    "_unknown_39" smallint NOT NULL,
    "recast100ms" integer NOT NULL,
    "cooldown_group" smallint NOT NULL,
    "additional_cooldown_group" smallint NOT NULL,
    "max_charges" smallint NOT NULL,
    "attack_type" integer NOT NULL,
    "aspect" smallint NOT NULL,
    "action_proc_status" integer NOT NULL,
    "_unknown_47" smallint NOT NULL,
    "status_gain_self" integer NOT NULL,
    "unlock_link" integer NOT NULL,
    "class_job_category" integer NOT NULL,
    "_unknown_51" smallint NOT NULL,
    "_unknown_52" boolean NOT NULL,
    "affects_position" boolean NOT NULL,
    "omen" integer NOT NULL,
    "_unknown_55" integer NOT NULL,
    "is_pvp" boolean NOT NULL,
    "_unknown_57" boolean NOT NULL,
    "_unknown_58" boolean NOT NULL,
    "_unknown_59" boolean NOT NULL,
    "_unknown_60" boolean NOT NULL,
    "_unknown_61" boolean NOT NULL,
    "_unknown_62" boolean NOT NULL,
    "_unknown_63" boolean NOT NULL,
    "_unknown_64" boolean NOT NULL,
    "_unknown_65" smallint NOT NULL,
    "_unknown_66" boolean NOT NULL,
    "_unknown_67" boolean NOT NULL,
    "is_player_action" boolean NOT NULL,
    "_unknown_69" smallint NOT NULL
);


ALTER TABLE "public"."actions2" OWNER TO "postgres";


ALTER TABLE ONLY "analysis"."fight_events"
    ADD CONSTRAINT "fight_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "analysis"."report_actors"
    ADD CONSTRAINT "report_actors_pkey" PRIMARY KEY ("id", "report_id");



ALTER TABLE ONLY "analysis"."report_fights"
    ADD CONSTRAINT "report_fights_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "analysis"."reports"
    ADD CONSTRAINT "reports_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."actions2"
    ADD CONSTRAINT "actions2_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."actions"
    ADD CONSTRAINT "actions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "analysis"."fight_events"
    ADD CONSTRAINT "fight_events_fight_id_fkey" FOREIGN KEY ("fight_id") REFERENCES "analysis"."report_fights"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "analysis"."report_actors"
    ADD CONSTRAINT "report_actors_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "analysis"."reports"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "analysis"."report_fights"
    ADD CONSTRAINT "report_fights_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "analysis"."reports"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Access own reports" ON "analysis"."reports" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "owner")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "owner"));



CREATE POLICY "access own reports" ON "analysis"."report_fights" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "reports"."owner"
   FROM "analysis"."reports"
  WHERE ("reports"."id" = "report_fights"."report_id")))) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "reports"."owner"
   FROM "analysis"."reports"
  WHERE ("reports"."id" = "report_fights"."report_id"))));



CREATE POLICY "edit own reports" ON "analysis"."fight_events" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "reports"."owner"
   FROM "analysis"."reports"
  WHERE ("reports"."id" = ( SELECT "report_fights"."report_id"
           FROM "analysis"."report_fights"
          WHERE ("report_fights"."id" = "fight_events"."fight_id")))))) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "reports"."owner"
   FROM "analysis"."reports"
  WHERE ("reports"."id" = ( SELECT "report_fights"."report_id"
           FROM "analysis"."report_fights"
          WHERE ("report_fights"."id" = "fight_events"."fight_id"))))));



CREATE POLICY "edit own reports" ON "analysis"."report_actors" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "reports"."owner"
   FROM "analysis"."reports"
  WHERE ("reports"."id" = "report_actors"."report_id")))) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = ( SELECT "reports"."owner"
   FROM "analysis"."reports"
  WHERE ("reports"."id" = "report_actors"."report_id"))));



ALTER TABLE "analysis"."fight_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "analysis"."report_actors" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "analysis"."report_fights" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "analysis"."reports" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."actions" TO "anon";
GRANT ALL ON TABLE "public"."actions" TO "authenticated";
GRANT ALL ON TABLE "public"."actions" TO "service_role";



GRANT ALL ON TABLE "public"."actions2" TO "anon";
GRANT ALL ON TABLE "public"."actions2" TO "authenticated";
GRANT ALL ON TABLE "public"."actions2" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
